import type { MovieData } from '../types/movie'
import { getMovieVideoUrl } from '../config/movies'

type LegacyMovieData = Omit<MovieData, 'id'> & { id: 'findingNemo' }

export const findingNemoData: LegacyMovieData = {
  id: 'findingNemo',
  title: 'Finding Nemo',
  description:
    'Marlin crosses the ocean to find Nemo while learning to trust others and let his son grow.',
  runtime: '1h 40m',
  genre: 'Family · Adventure',
  rating: 'G',
  accessibilityTags: [
    'Audio Description',
    'High Contrast Friendly',
    'Simple Language Prompts',
    'Keyboard Navigation',
    'Reduced Motion Supported',
  ],
  posterUrl:
    'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
  videoSrc: getMovieVideoUrl('findingNemo'),
  subtitleSrc: '',
  companionTheme: 'ocean',
  scenes: [
    {
      sceneId: 'nemo-01',
      timestamp: 0,
      subtitle: 'Marlin checks the reef edge with Nemo before school.',
      prompts: [
        { id: 'who', label: 'Who is this?', question: 'Who are these fish?', explanation: 'Marlin is Nemo\'s father. Nemo is his curious son.' },
        { id: 'why', label: 'Why are they nervous?', question: 'Why is Marlin worried?', explanation: 'Marlin lost his family before, so he is extra protective.' },
        { id: 'next', label: 'What happens next?', question: 'What is about to happen?', explanation: 'Nemo will challenge Marlin\'s safety rules.' },
      ],
      characterList: [
        { id: 'marlin', name: 'Marlin', role: 'Father', emotionalState: 'Anxious' },
        { id: 'nemo', name: 'Nemo', role: 'Son', emotionalState: 'Curious' },
      ],
      emotion: 'Protective tension',
      relationshipGraph: [{ from: 'Marlin', to: 'Nemo', label: 'Parent guidance' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'School day begins' },
        { id: 't2', time: 'Now', label: 'Safety warning at reef edge' },
        { id: 't3', time: 'Next', label: 'Nemo pushes boundaries' },
      ],
      causeEffectData: {
        cause: 'Marlin fears danger',
        action: 'He warns Nemo repeatedly',
        effect: 'Nemo feels controlled',
      },
      companionPosition: { x: 34, y: 58 },
      highlightObject: { name: 'Reef edge', reason: 'Marks safe vs risky zone' },
      voiceNarration: 'This moment establishes trust and fear between father and son.',
    },
    {
      sceneId: 'nemo-02',
      timestamp: 45,
      subtitle: 'Nemo swims toward the boat to prove himself.',
      prompts: [
        { id: 'who', label: 'Who is this?', question: 'Who is making the risky choice?', explanation: 'Nemo takes a risk to prove he is brave.' },
        { id: 'why', label: 'Why this matters?', question: 'Why is this scene important?', explanation: 'This choice triggers the whole rescue story.' },
        { id: 'change', label: 'What changed?', question: 'What changed in emotions?', explanation: 'Curiosity changed into danger and panic.' },
      ],
      characterList: [
        { id: 'nemo', name: 'Nemo', role: 'Son', emotionalState: 'Defiant' },
        { id: 'marlin', name: 'Marlin', role: 'Father', emotionalState: 'Terrified' },
      ],
      emotion: 'Defiance and panic',
      relationshipGraph: [{ from: 'Nemo', to: 'Marlin', label: 'Wants independence' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Argument about safety' },
        { id: 't2', time: 'Now', label: 'Nemo approaches boat' },
        { id: 't3', time: 'Next', label: 'Capture by divers' },
      ],
      causeEffectData: {
        cause: 'Nemo feels underestimated',
        action: 'He swims to the boat',
        effect: 'Divers capture him',
      },
      companionPosition: { x: 62, y: 46 },
      highlightObject: { name: 'Boat', reason: 'Danger source and plot trigger' },
      voiceNarration: 'Nemo is trying to prove he can handle danger alone.',
    },
    {
      sceneId: 'nemo-03',
      timestamp: 90,
      subtitle: 'Marlin meets Dory and starts the journey.',
      prompts: [
        { id: 'who', label: 'Who is this?', question: 'Who is Dory?', explanation: 'Dory is optimistic and helps Marlin despite memory issues.' },
        { id: 'sad', label: 'Why are they sad?', question: 'Why is Marlin upset?', explanation: 'He is overwhelmed and afraid Nemo is gone forever.' },
        { id: 'next', label: 'What happens next?', question: 'How does this help?', explanation: 'Dory keeps Marlin moving and hopeful.' },
      ],
      characterList: [
        { id: 'marlin', name: 'Marlin', role: 'Father', emotionalState: 'Desperate' },
        { id: 'dory', name: 'Dory', role: 'Companion', emotionalState: 'Hopeful' },
      ],
      emotion: 'Fear with new hope',
      relationshipGraph: [{ from: 'Dory', to: 'Marlin', label: 'Supportive ally' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Nemo captured' },
        { id: 't2', time: 'Now', label: 'Dory joins Marlin' },
        { id: 't3', time: 'Next', label: 'Ocean journey begins' },
      ],
      causeEffectData: {
        cause: 'Marlin is lost and afraid',
        action: 'Dory offers help',
        effect: 'They begin searching together',
      },
      companionPosition: { x: 44, y: 52 },
      highlightObject: { name: 'Mask clue', reason: 'Leads them toward Sydney' },
      voiceNarration: 'A partnership forms: caution and optimism together.',
    },
    {
      sceneId: 'nemo-04',
      timestamp: 135,
      subtitle: 'They navigate jellyfish and teamwork pressure.',
      prompts: [
        { id: 'scene', label: 'Explain this scene', question: 'What challenge is this?', explanation: 'They cross a dangerous jellyfish field by coordinating movement.' },
        { id: 'change', label: 'What changed?', question: 'How did Marlin change?', explanation: 'He starts trusting Dory\'s instincts.' },
        { id: 'next', label: 'What happens next?', question: 'What follows this challenge?', explanation: 'They become a stronger team after surviving together.' },
      ],
      characterList: [
        { id: 'marlin', name: 'Marlin', role: 'Father', emotionalState: 'Worried but adapting' },
        { id: 'dory', name: 'Dory', role: 'Companion', emotionalState: 'Confident' },
      ],
      emotion: 'Risk and trust',
      relationshipGraph: [{ from: 'Marlin', to: 'Dory', label: 'Growing trust' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Following clues' },
        { id: 't2', time: 'Now', label: 'Jellyfish crossing' },
        { id: 't3', time: 'Next', label: 'Deeper partnership' },
      ],
      causeEffectData: {
        cause: 'A dangerous route blocks progress',
        action: 'They move in rhythm through jellyfish',
        effect: 'Mutual trust increases',
      },
      companionPosition: { x: 51, y: 42 },
      highlightObject: { name: 'Jellyfish lane', reason: 'Defines safe movement path' },
      voiceNarration: 'They survive by cooperation, not control.',
    },
    {
      sceneId: 'nemo-05',
      timestamp: 180,
      subtitle: 'Nemo adapts in the fish tank and learns strategy.',
      prompts: [
        { id: 'who', label: 'Who is this?', question: 'Who are these tank fish?', explanation: 'Gill leads the tank group and mentors Nemo.' },
        { id: 'why', label: 'Why this matters?', question: 'Why is this scene key?', explanation: 'Nemo starts taking smart, careful initiative.' },
        { id: 'next', label: 'What happens next?', question: 'What is Nemo building toward?', explanation: 'He prepares to help execute an escape plan.' },
      ],
      characterList: [
        { id: 'nemo', name: 'Nemo', role: 'Son', emotionalState: 'Determined' },
        { id: 'gill', name: 'Gill', role: 'Mentor', emotionalState: 'Focused' },
      ],
      emotion: 'Determination',
      relationshipGraph: [{ from: 'Gill', to: 'Nemo', label: 'Mentor support' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Shock in tank' },
        { id: 't2', time: 'Now', label: 'Learns escape strategy' },
        { id: 't3', time: 'Next', label: 'Attempts execution' },
      ],
      causeEffectData: {
        cause: 'Nemo needs agency',
        action: 'He trains with tank fish',
        effect: 'Confidence and skills grow',
      },
      companionPosition: { x: 35, y: 49 },
      highlightObject: { name: 'Filter intake', reason: 'Core target in escape plan' },
      voiceNarration: 'Nemo is no longer only a victim; he becomes proactive.',
    },
    {
      sceneId: 'nemo-06',
      timestamp: 225,
      subtitle: 'Marlin and Dory drift with sea turtles on the current.',
      prompts: [
        { id: 'scene', label: 'Explain this scene', question: 'What is happening on the current?', explanation: 'The turtles provide safe fast travel and perspective.' },
        { id: 'sad', label: 'Why are they sad?', question: 'Why is Marlin still tense?', explanation: 'He fears every delay could cost Nemo\'s safety.' },
        { id: 'change', label: 'What changed?', question: 'What changed in Marlin?', explanation: 'He allows lighter moments and less control.' },
      ],
      characterList: [
        { id: 'marlin', name: 'Marlin', role: 'Father', emotionalState: 'Cautiously hopeful' },
        { id: 'dory', name: 'Dory', role: 'Companion', emotionalState: 'Relaxed' },
      ],
      emotion: 'Relief and cautious hope',
      relationshipGraph: [{ from: 'Dory', to: 'Marlin', label: 'Keeps him grounded' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'High-risk travel' },
        { id: 't2', time: 'Now', label: 'Current with turtles' },
        { id: 't3', time: 'Next', label: 'Approaching Sydney' },
      ],
      causeEffectData: {
        cause: 'They need faster route',
        action: 'Join turtle current',
        effect: 'Gain speed and confidence',
      },
      companionPosition: { x: 57, y: 39 },
      highlightObject: { name: 'East Australian Current', reason: 'Major travel acceleration' },
      voiceNarration: 'The journey gains momentum and emotional balance.',
    },
    {
      sceneId: 'nemo-07',
      timestamp: 270,
      subtitle: 'Nemo faces a difficult escape attempt.',
      prompts: [
        { id: 'who', label: 'Who is this?', question: 'Who helps Nemo here?', explanation: 'The tank crew supports Nemo, but risk is high.' },
        { id: 'scene', label: 'Explain this scene', question: 'Why does this feel intense?', explanation: 'Nemo is physically tested while trying to prove himself.' },
        { id: 'next', label: 'What happens next?', question: 'What follows this failure?', explanation: 'Nemo regroups and tries again with more care.' },
      ],
      characterList: [
        { id: 'nemo', name: 'Nemo', role: 'Son', emotionalState: 'Strained but brave' },
        { id: 'gill', name: 'Gill', role: 'Mentor', emotionalState: 'Protective' },
      ],
      emotion: 'High stakes resolve',
      relationshipGraph: [{ from: 'Tank Group', to: 'Nemo', label: 'Collective support' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Plan preparation' },
        { id: 't2', time: 'Now', label: 'Risky attempt' },
        { id: 't3', time: 'Next', label: 'Recovery and retry' },
      ],
      causeEffectData: {
        cause: 'Escape requires precision',
        action: 'Nemo attempts under pressure',
        effect: 'He learns resilience',
      },
      companionPosition: { x: 63, y: 52 },
      highlightObject: { name: 'Tank filter', reason: 'Main obstacle to freedom' },
      voiceNarration: 'Setbacks become training for Nemo\'s growth.',
    },
    {
      sceneId: 'nemo-08',
      timestamp: 315,
      subtitle: 'Marlin hears a story about his own rescue mission.',
      prompts: [
        { id: 'scene', label: 'Explain this scene', question: 'Why is this moment emotional?', explanation: 'Marlin realizes Nemo is inspired by his effort.' },
        { id: 'change', label: 'What changed?', question: 'How does this shift Marlin?', explanation: 'He shifts from fear to belief in Nemo.' },
        { id: 'next', label: 'What happens next?', question: 'What does this motivate?', explanation: 'Marlin pushes forward with new confidence.' },
      ],
      characterList: [
        { id: 'marlin', name: 'Marlin', role: 'Father', emotionalState: 'Moved' },
        { id: 'dory', name: 'Dory', role: 'Companion', emotionalState: 'Encouraging' },
      ],
      emotion: 'Hopeful turning point',
      relationshipGraph: [{ from: 'Marlin', to: 'Nemo', label: 'Mutual belief' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Exhausted pursuit' },
        { id: 't2', time: 'Now', label: 'Learns his story spread' },
        { id: 't3', time: 'Next', label: 'Renewed effort' },
      ],
      causeEffectData: {
        cause: 'News of Marlin\'s journey reaches others',
        action: 'Marlin hears Nemo\'s perspective',
        effect: 'Emotional strength increases',
      },
      companionPosition: { x: 49, y: 45 },
      highlightObject: { name: 'Pelican transport', reason: 'Connects separate story lines' },
      voiceNarration: 'The rescue mission becomes a shared story of love and courage.',
    },
    {
      sceneId: 'nemo-09',
      timestamp: 360,
      subtitle: 'Father and son reunite during a net rescue.',
      prompts: [
        { id: 'who', label: 'Who is this?', question: 'Who helps in the rescue?', explanation: 'Nemo and Dory coordinate the fish to swim down together.' },
        { id: 'why', label: 'Why this matters?', question: 'Why is this climax important?', explanation: 'Marlin learns to trust Nemo\'s capability.' },
        { id: 'change', label: 'What changed?', question: 'What changed in their relationship?', explanation: 'Control becomes trust and collaboration.' },
      ],
      characterList: [
        { id: 'marlin', name: 'Marlin', role: 'Father', emotionalState: 'Proud and relieved' },
        { id: 'nemo', name: 'Nemo', role: 'Son', emotionalState: 'Confident' },
        { id: 'dory', name: 'Dory', role: 'Companion', emotionalState: 'Focused' },
      ],
      emotion: 'Relief and pride',
      relationshipGraph: [{ from: 'Nemo', to: 'Marlin', label: 'Earned trust' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Chaos in fishing net' },
        { id: 't2', time: 'Now', label: 'Nemo leads coordinated push' },
        { id: 't3', time: 'Next', label: 'Mass rescue success' },
      ],
      causeEffectData: {
        cause: 'Fish are trapped',
        action: 'Nemo directs synchronized escape',
        effect: 'Net breaks and fish survive',
      },
      companionPosition: { x: 52, y: 57 },
      highlightObject: { name: 'Fishing net', reason: 'Main external threat in climax' },
      voiceNarration: 'Nemo demonstrates leadership, and Marlin finally trusts him.',
    },
    {
      sceneId: 'nemo-10',
      timestamp: 405,
      subtitle: 'The family returns to a calmer, trusting routine.',
      prompts: [
        { id: 'next', label: 'What happens next?', question: 'What changed after the adventure?', explanation: 'Marlin supports Nemo with confidence, not fear.' },
        { id: 'scene', label: 'Explain this scene', question: 'Why does this ending feel peaceful?', explanation: 'Conflict is resolved through growth on both sides.' },
        { id: 'change', label: 'What changed?', question: 'What changed in Marlin?', explanation: 'He keeps caring deeply, but no longer blocks Nemo\'s growth.' },
      ],
      characterList: [
        { id: 'marlin', name: 'Marlin', role: 'Father', emotionalState: 'Calm' },
        { id: 'nemo', name: 'Nemo', role: 'Son', emotionalState: 'Secure' },
      ],
      emotion: 'Resolution and trust',
      relationshipGraph: [{ from: 'Marlin', to: 'Nemo', label: 'Supportive trust' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'High-stakes rescue' },
        { id: 't2', time: 'Now', label: 'Warm reunion' },
        { id: 't3', time: 'Next', label: 'Healthier family balance' },
      ],
      causeEffectData: {
        cause: 'Shared hardship and success',
        action: 'They reconnect with new perspective',
        effect: 'Relationship matures',
      },
      companionPosition: { x: 41, y: 40 },
      highlightObject: { name: 'School route', reason: 'Symbol of normal life restored' },
      voiceNarration: 'The story closes with trust, growth, and emotional safety.',
    },
  ],
}
