import type { MovieData } from '../types/movie'

type LegacyMovieData = Omit<MovieData, 'id'> & { id: 'insideOut' }

export const insideOutData: LegacyMovieData = {
  id: 'insideOut',
  title: 'Inside Out',
  description:
    'Riley\'s emotions struggle for balance after a major move, revealing that sadness is essential too.',
  runtime: '1h 35m',
  genre: 'Family · Comedy',
  rating: 'PG',
  accessibilityTags: [
    'Audio Description',
    'High Contrast Friendly',
    'Simple Language Prompts',
    'Keyboard Navigation',
    'Reduced Motion Supported',
  ],
  posterUrl:
    'https://images.unsplash.com/photo-1496497243327-9dccd845c35f?auto=format&fit=crop&w=1200&q=80',
  videoSrc: '/movies/inside-out-demo.mp4',
  subtitleSrc: '',
  companionTheme: 'sun',
  scenes: [
    {
      sceneId: 'inside-01',
      timestamp: 0,
      subtitle: 'Riley enters her new school and tries to stay positive.',
      prompts: [
        { id: 'who', label: 'Who is this?', question: 'Who controls Riley here?', explanation: 'Joy leads most decisions while Sadness stays nearby.' },
        { id: 'scene', label: 'Explain this scene', question: 'What is Riley trying to do?', explanation: 'She is trying to appear confident in a stressful new environment.' },
        { id: 'sad', label: 'Why are they sad?', question: 'Why does this feel heavy?', explanation: 'Riley misses her old life in Minnesota.' },
      ],
      characterList: [
        { id: 'joy', name: 'Joy', role: 'Emotion lead', emotionalState: 'Energetic' },
        { id: 'sadness', name: 'Sadness', role: 'Emotion', emotionalState: 'Muted' },
      ],
      emotion: 'Forced optimism',
      relationshipGraph: [{ from: 'Joy', to: 'Sadness', label: 'Trying to limit influence' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Move to new city' },
        { id: 't2', time: 'Now', label: 'First class intro' },
        { id: 't3', time: 'Next', label: 'Unexpected tears' },
      ],
      causeEffectData: {
        cause: 'New environment stress',
        action: 'Riley recalls old memories in class',
        effect: 'Emotions become unstable',
      },
      companionPosition: { x: 58, y: 45 },
      highlightObject: { name: 'Memory orb', reason: 'Represents emotional shift' },
      voiceNarration: 'Riley is trying to hold it together while internally overwhelmed.',
    },
    {
      sceneId: 'inside-02',
      timestamp: 45,
      subtitle: 'A core memory changes color after Sadness touches it.',
      prompts: [
        { id: 'why', label: 'Why this matters?', question: 'Why is this a big moment?', explanation: 'Core memories shape Riley\'s identity, so color change is huge.' },
        { id: 'change', label: 'What changed?', question: 'What changed emotionally?', explanation: 'A joyful memory is now linked to sadness.' },
        { id: 'next', label: 'What happens next?', question: 'What does this trigger?', explanation: 'The memory system destabilizes and key emotions are displaced.' },
      ],
      characterList: [
        { id: 'joy', name: 'Joy', role: 'Emotion lead', emotionalState: 'Alarmed' },
        { id: 'sadness', name: 'Sadness', role: 'Emotion', emotionalState: 'Conflicted' },
      ],
      emotion: 'Shock and confusion',
      relationshipGraph: [{ from: 'Sadness', to: 'Joy', label: 'Unintentional disruption' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Stable control console' },
        { id: 't2', time: 'Now', label: 'Core memory turns blue' },
        { id: 't3', time: 'Next', label: 'Control loss begins' },
      ],
      causeEffectData: {
        cause: 'Sadness touches core memory',
        action: 'Memory color changes',
        effect: 'Identity islands become unstable',
      },
      companionPosition: { x: 42, y: 52 },
      highlightObject: { name: 'Core memory rack', reason: 'Primary stability system' },
      voiceNarration: 'Sadness is not malicious; she reflects Riley\'s real emotional needs.',
    },
    {
      sceneId: 'inside-03',
      timestamp: 90,
      subtitle: 'Joy and Sadness are pulled out of Headquarters.',
      prompts: [
        { id: 'scene', label: 'Explain this scene', question: 'Why is this dangerous?', explanation: 'Without Joy and Sadness, Riley loses emotional balance.' },
        { id: 'who', label: 'Who is this?', question: 'Who remains in control?', explanation: 'Anger, Fear, and Disgust run operations.' },
        { id: 'next', label: 'What happens next?', question: 'What follows this separation?', explanation: 'Riley starts making reactive choices.' },
      ],
      characterList: [
        { id: 'joy', name: 'Joy', role: 'Emotion lead', emotionalState: 'Determined' },
        { id: 'sadness', name: 'Sadness', role: 'Emotion', emotionalState: 'Uncertain' },
        { id: 'anger', name: 'Anger', role: 'Emotion', emotionalState: 'Impatient' },
      ],
      emotion: 'Instability',
      relationshipGraph: [{ from: 'Anger', to: 'Console', label: 'Temporary control' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Memory disturbance' },
        { id: 't2', time: 'Now', label: 'Joy/Sadness ejected' },
        { id: 't3', time: 'Next', label: 'Reactive behavior spikes' },
      ],
      causeEffectData: {
        cause: 'Control conflict at console',
        action: 'Joy and Sadness get displaced',
        effect: 'Remaining emotions overcompensate',
      },
      companionPosition: { x: 55, y: 58 },
      highlightObject: { name: 'Console panel', reason: 'Represents behavioral control' },
      voiceNarration: 'Riley begins operating without crucial emotional range.',
    },
    {
      sceneId: 'inside-04',
      timestamp: 135,
      subtitle: 'Riley struggles at dinner and disconnects from her parents.',
      prompts: [
        { id: 'sad', label: 'Why are they sad?', question: 'Why does dinner escalate?', explanation: 'Riley feels unseen and overloaded after the move.' },
        { id: 'change', label: 'What changed?', question: 'What changed in family tone?', explanation: 'Conversation shifts from support to conflict.' },
        { id: 'next', label: 'What happens next?', question: 'How does this impact Riley?', explanation: 'She withdraws further and feels isolated.' },
      ],
      characterList: [
        { id: 'riley', name: 'Riley', role: 'Main character', emotionalState: 'Overwhelmed' },
        { id: 'anger', name: 'Anger', role: 'Emotion', emotionalState: 'Dominant' },
      ],
      emotion: 'Frustration and isolation',
      relationshipGraph: [{ from: 'Riley', to: 'Parents', label: 'Communication strain' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'School stress' },
        { id: 't2', time: 'Now', label: 'Dinner argument' },
        { id: 't3', time: 'Next', label: 'Social withdrawal' },
      ],
      causeEffectData: {
        cause: 'Unprocessed sadness',
        action: 'Anger drives responses',
        effect: 'Family conflict rises',
      },
      companionPosition: { x: 48, y: 42 },
      highlightObject: { name: 'Dinner table', reason: 'Family communication focal point' },
      voiceNarration: 'Without emotional balance, misunderstandings spread quickly.',
    },
    {
      sceneId: 'inside-05',
      timestamp: 180,
      subtitle: 'Joy and Sadness cross memory zones to return to Headquarters.',
      prompts: [
        { id: 'scene', label: 'Explain this scene', question: 'What are these zones?', explanation: 'They are symbolic areas of Riley\'s mind and memory processing.' },
        { id: 'who', label: 'Who is this?', question: 'Who helps along the way?', explanation: 'Bing Bong supports their path with sacrifice and empathy.' },
        { id: 'why', label: 'Why this matters?', question: 'Why is this journey important?', explanation: 'Joy begins understanding Sadness as necessary, not harmful.' },
      ],
      characterList: [
        { id: 'joy', name: 'Joy', role: 'Emotion lead', emotionalState: 'Driven' },
        { id: 'sadness', name: 'Sadness', role: 'Emotion', emotionalState: 'Empathetic' },
        { id: 'bingbong', name: 'Bing Bong', role: 'Memory friend', emotionalState: 'Loyal' },
      ],
      emotion: 'Discovery and empathy',
      relationshipGraph: [{ from: 'Joy', to: 'Sadness', label: 'Growing respect' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Ejected from HQ' },
        { id: 't2', time: 'Now', label: 'Mind-world traversal' },
        { id: 't3', time: 'Next', label: 'Perspective shift' },
      ],
      causeEffectData: {
        cause: 'Need to restore emotional balance',
        action: 'Cross memory regions',
        effect: 'Joy rethinks Sadness\'s role',
      },
      companionPosition: { x: 36, y: 50 },
      highlightObject: { name: 'Memory shelves', reason: 'Represent identity and recall' },
      voiceNarration: 'The emotional journey reframes what healthy coping means.',
    },
    {
      sceneId: 'inside-06',
      timestamp: 225,
      subtitle: 'Riley becomes emotionally numb and stops engaging.',
      prompts: [
        { id: 'sad', label: 'Why are they sad?', question: 'Why is Riley shutting down?', explanation: 'Disconnected from Joy and Sadness, she cannot process feelings properly.' },
        { id: 'change', label: 'What changed?', question: 'What changed in behavior?', explanation: 'She shifts from emotional responses to emptiness.' },
        { id: 'next', label: 'What happens next?', question: 'What decision forms now?', explanation: 'She considers running away to recover old comfort.' },
      ],
      characterList: [
        { id: 'riley', name: 'Riley', role: 'Main character', emotionalState: 'Numb' },
        { id: 'fear', name: 'Fear', role: 'Emotion', emotionalState: 'Uncertain' },
      ],
      emotion: 'Numbness',
      relationshipGraph: [{ from: 'Riley', to: 'Self', label: 'Internal disconnection' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Family conflict' },
        { id: 't2', time: 'Now', label: 'Emotional flatline' },
        { id: 't3', time: 'Next', label: 'Risky plan forms' },
      ],
      causeEffectData: {
        cause: 'Missing emotional integration',
        action: 'Riley disengages',
        effect: 'Impulsive escape thinking',
      },
      companionPosition: { x: 64, y: 44 },
      highlightObject: { name: 'Bus ticket', reason: 'Represents escape attempt' },
      voiceNarration: 'Emotional numbness can look calm but signals deep distress.',
    },
    {
      sceneId: 'inside-07',
      timestamp: 270,
      subtitle: 'Joy realizes sadness helps Riley receive comfort from others.',
      prompts: [
        { id: 'why', label: 'Why this matters?', question: 'Why is sadness useful?', explanation: 'Sadness communicates need and invites support.' },
        { id: 'scene', label: 'Explain this scene', question: 'What does Joy learn?', explanation: 'Joy learns that constant positivity can block healing.' },
        { id: 'change', label: 'What changed?', question: 'What changed in Joy?', explanation: 'She stops controlling everything and shares space.' },
      ],
      characterList: [
        { id: 'joy', name: 'Joy', role: 'Emotion lead', emotionalState: 'Reflective' },
        { id: 'sadness', name: 'Sadness', role: 'Emotion', emotionalState: 'Steady' },
      ],
      emotion: 'Insight',
      relationshipGraph: [{ from: 'Joy', to: 'Sadness', label: 'Acceptance' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Resistance to sadness' },
        { id: 't2', time: 'Now', label: 'Insight about empathy' },
        { id: 't3', time: 'Next', label: 'Collaborative control' },
      ],
      causeEffectData: {
        cause: 'Witnessing comforting memory pattern',
        action: 'Joy reframes sadness',
        effect: 'Emotional integration becomes possible',
      },
      companionPosition: { x: 40, y: 40 },
      highlightObject: { name: 'Memory playback', reason: 'Shows emotional cause and effect clearly' },
      voiceNarration: 'Sadness helps Riley be understood and supported.',
    },
    {
      sceneId: 'inside-08',
      timestamp: 315,
      subtitle: 'Riley boards a bus but pauses as emotions reconnect.',
      prompts: [
        { id: 'next', label: 'What happens next?', question: 'Will Riley leave?', explanation: 'She stops and returns home to talk honestly.' },
        { id: 'scene', label: 'Explain this scene', question: 'Why is this pivotal?', explanation: 'This is the turning point from escape to emotional expression.' },
        { id: 'change', label: 'What changed?', question: 'What changed inside?', explanation: 'Joy and Sadness cooperate at the console.' },
      ],
      characterList: [
        { id: 'riley', name: 'Riley', role: 'Main character', emotionalState: 'Conflicted' },
        { id: 'joy', name: 'Joy', role: 'Emotion lead', emotionalState: 'Supportive' },
        { id: 'sadness', name: 'Sadness', role: 'Emotion', emotionalState: 'Grounding' },
      ],
      emotion: 'Conflict resolving',
      relationshipGraph: [{ from: 'Joy + Sadness', to: 'Riley', label: 'Shared guidance' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Runaway plan' },
        { id: 't2', time: 'Now', label: 'Bus hesitation' },
        { id: 't3', time: 'Next', label: 'Return home' },
      ],
      causeEffectData: {
        cause: 'Emotions re-synchronize',
        action: 'Riley pauses escape',
        effect: 'Constructive conversation begins',
      },
      companionPosition: { x: 53, y: 56 },
      highlightObject: { name: 'Bus aisle', reason: 'Represents final chance to turn back' },
      voiceNarration: 'The most important action is choosing connection over avoidance.',
    },
    {
      sceneId: 'inside-09',
      timestamp: 360,
      subtitle: 'Riley tells her parents she is sad and misses home.',
      prompts: [
        { id: 'sad', label: 'Why are they sad?', question: 'Why does this scene feel emotional?', explanation: 'Riley finally allows sadness and receives support.' },
        { id: 'who', label: 'Who is this?', question: 'Who helps Riley recover?', explanation: 'Her parents validate her feelings and reconnect with her.' },
        { id: 'why', label: 'Why this matters?', question: 'Why is this healing?', explanation: 'Naming sadness reduces isolation and restores trust.' },
      ],
      characterList: [
        { id: 'riley', name: 'Riley', role: 'Main character', emotionalState: 'Vulnerable' },
        { id: 'parents', name: 'Parents', role: 'Support system', emotionalState: 'Compassionate' },
      ],
      emotion: 'Relief through vulnerability',
      relationshipGraph: [{ from: 'Riley', to: 'Parents', label: 'Open communication restored' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Emotional shutdown' },
        { id: 't2', time: 'Now', label: 'Honest expression' },
        { id: 't3', time: 'Next', label: 'Family support' },
      ],
      causeEffectData: {
        cause: 'Sadness is expressed directly',
        action: 'Riley asks for emotional support',
        effect: 'Connection and safety increase',
      },
      companionPosition: { x: 46, y: 48 },
      highlightObject: { name: 'Family hug', reason: 'Physical signal of emotional safety' },
      voiceNarration: 'Vulnerability creates the path to emotional recovery.',
    },
    {
      sceneId: 'inside-10',
      timestamp: 405,
      subtitle: 'A new balanced memory forms with mixed emotions.',
      prompts: [
        { id: 'change', label: 'What changed?', question: 'What changed in Riley\'s emotional system?', explanation: 'Memories now include multiple emotions, not just one.' },
        { id: 'next', label: 'What happens next?', question: 'What does this mean for Riley?', explanation: 'She can adapt more flexibly to future challenges.' },
        { id: 'scene', label: 'Explain this scene', question: 'Why is this ending mature?', explanation: 'It shows emotional complexity as a sign of growth.' },
      ],
      characterList: [
        { id: 'joy', name: 'Joy', role: 'Emotion lead', emotionalState: 'Balanced' },
        { id: 'sadness', name: 'Sadness', role: 'Emotion', emotionalState: 'Integrated' },
      ],
      emotion: 'Integrated resilience',
      relationshipGraph: [{ from: 'All emotions', to: 'Riley', label: 'Collaborative regulation' }],
      timelineData: [
        { id: 't1', time: 'Before', label: 'Single-emotion memories' },
        { id: 't2', time: 'Now', label: 'Mixed emotion memory appears' },
        { id: 't3', time: 'Next', label: 'Healthier emotional future' },
      ],
      causeEffectData: {
        cause: 'Joy and Sadness cooperate',
        action: 'New memory forms with blended emotions',
        effect: 'Riley gains emotional maturity',
      },
      companionPosition: { x: 59, y: 41 },
      highlightObject: { name: 'Blended memory orb', reason: 'Symbol of emotional integration' },
      voiceNarration: 'Healthy growth includes joy, sadness, and everything between.',
    },
  ],
}
