import type { MovieData } from '../types/movie'
import { getMovieVideoUrl, movieAssets } from '../config/movies'

export const spriteFrightData: MovieData = {
  id: 'spriteFright', title: 'Sprite Fright',
  description: 'A group of teenagers hiking through the woods clash over Ellie’s love of nature before they encounter the forest sprites.',
  runtime: '11 min', genre: 'Fantasy · Animation', rating: 'All ages',
  accessibilityTags: ['Simple Language Prompts', 'Keyboard Navigation', 'Reduced Motion Supported'], posterUrl: movieAssets.spriteFright.posterUrl, videoSrc: getMovieVideoUrl('spriteFright'), subtitleSrc: movieAssets.spriteFright.subtitleSrc, companionTheme: 'ocean',
  canonicalCharacters: [
    { id: 'ellie', name: 'Ellie', description: 'Nature lover', personality: 'Curious and observant', goals: ['Study the forest'], relationships: ['Rex and Victoria are impatient with her detours'], firstAppearance: 0, importantInformation: ['She uses Latin names for animals.'], visualDescription: 'Teen girl with blue hair ties and nature equipment', confidenceThreshold: 0.7 },
    { id: 'rex', name: 'Rex', description: 'Aggressive jock', personality: 'Impatient', goals: ['Keep the group moving'], relationships: ['Annoyed with Ellie'], firstAppearance: 0, importantInformation: ['He carries a bat.'], visualDescription: 'Blonde hair, blue vest, carries a bat', confidenceThreshold: 0.7 },
    { id: 'victoria', name: 'Victoria', description: 'Teenager', personality: 'Supports Rex', goals: ['Finish the trip'], relationships: ['Travels with Rex and Ellie'], firstAppearance: 0, importantInformation: ['She is part of the hiking group.'], visualDescription: 'Pink hair and sunglasses', confidenceThreshold: 0.7 },
    { id: 'sprites', name: 'Sprites', description: 'Forest creatures', personality: 'Protective of their forest', goals: ['Protect the forest'], relationships: ['React to the teenagers entering their home'], firstAppearance: 135, importantInformation: ['They do not appear in the opening conversation.'], visualDescription: 'Small mushroom-like forest creatures', confidenceThreshold: 0.75 },
  ],
  scenes: [
    {
      sceneId: 'sf-01', timestamp: 0, subtitle: 'Rex complains to Victoria about Ellie stopping to study animals.',
      prompts: [
        { id: 'emotion', label: 'Feelings', question: 'Why is Rex upset with Ellie?', explanation: 'Rex is frustrated because Ellie keeps stopping to study animals while he wants the group to continue.' },
        { id: 'scene', label: 'Explain this scene', question: 'What is happening?', explanation: 'Rex and Victoria are discussing Ellie because her interest in nature is slowing their trip.' },
        { id: 'relationship', label: 'Relationships', question: 'Why are Rex and Ellie arguing?', explanation: 'Rex and Ellie have different priorities: Rex wants to move on, while Ellie wants to pay attention to nature.' },
      ],
      characterList: [{ id: 'rex', name: 'Rex', role: 'Aggressive jock', emotionalState: 'Frustrated and impatient' }, { id: 'victoria', name: 'Victoria', role: 'Teenager', emotionalState: 'Supporting Rex' }, { id: 'ellie', name: 'Ellie', role: 'Nature lover', emotionalState: 'Not visible' }],
      visibleCharacterIds: ['rex', 'victoria'], missingCharacterIds: ['ellie', 'sprites'], entityConfidence: { rex: 0.92, victoria: 0.88, ellie: 0, sprites: 0 }, entityEvidence: { rex: ['blue vest and bat are visible'], victoria: ['pink hair and sunglasses are visible'], ellie: ['mentioned in dialogue only'], sprites: ['not present before 02:15'] },
      promptSubjects: { emotion: ['rex'], scene: ['rex', 'victoria'], relationship: ['rex'] },
      dialogueReferences: [{ speakerEntityId: 'rex', targetEntityIds: ['ellie'], pronouns: [{ pronoun: 'her', resolvedEntityId: 'ellie', evidence: 'Ellie is the established subject of the complaint and is known for naming animals.' }] }],
      storyBeats: [
        { id: 'sf:intro-credits', startTime: 0, endTime: 22, phase: 'intro_credits', summary: 'Opening credits', visibleEntityIds: [], relationships: [], emotions: [], objects: [], causeEffect: [], memory: [], promptCandidates: [], drawerState: {}, confidence: 1, visualGrounding: { visibleEntityIds: [], missingEntityIds: ['ellie', 'rex', 'victoria', 'sprites'], confidence: {}, evidence: {}, visibleObjects: [] } },
        { id: 'sf:rex-victoria-conversation', startTime: 23, endTime: 135, phase: 'setup', summary: 'Rex and Victoria are discussing Ellie because her interest in nature is slowing their trip.', visibleEntityIds: ['rex', 'victoria'], relationships: ['Rex is annoyed with Ellie because they have different priorities.'], emotions: [{ character: 'Rex', emotion: 'Frustrated', explanation: 'Rex is frustrated because Ellie keeps stopping to study animals while he wants the group to continue.' }, { character: 'Victoria', emotion: 'Supportive', explanation: 'Victoria is supporting Rex in the conversation.' }], objects: ['Rex’s bat'], causeEffect: [{ cause: 'Ellie keeps stopping to study animals', effect: 'Rex complains to Victoria about the delay' }], memory: ['Ellie has been stopping to study animals during the trip.'], promptCandidates: [{ id: 'sf:rex-annoyed', triggerType: 'emotions', question: 'Why is Rex annoyed with Ellie?', explanation: 'Rex is frustrated because Ellie keeps stopping to study animals while he wants the group to continue.', difficultyCategory: 'Feelings', priority: 3, subjectEntityIds: ['rex'] }, { id: 'sf:conversation', triggerType: 'conversations', question: 'What are Rex and Victoria talking about?', explanation: 'They are complaining that Ellie’s interest in nature is slowing the trip.', difficultyCategory: 'Conversation', priority: 2, subjectEntityIds: ['rex', 'victoria'] }], drawerState: { conversationSummary: 'Rex complains to Victoria about Ellie stopping to study animals.', timelinePosition: 'The group’s disagreement begins', support: { characters: ['Rex: Frustrated and impatient.', 'Victoria: Supporting Rex.'], emotions: ['Rex is frustrated because Ellie keeps stopping to study animals.'], relationships: ['Rex is annoyed with Ellie because they have different priorities.'], memory: ['Ellie’s interest in nature has been slowing the trip.'] } }, confidence: 0.94, visualGrounding: { visibleEntityIds: ['rex', 'victoria'], missingEntityIds: ['ellie', 'sprites'], confidence: { rex: 0.92, victoria: 0.88, ellie: 0, sprites: 0 }, evidence: { rex: ['blue vest and bat are visible'], victoria: ['pink hair and sunglasses are visible'], ellie: ['mentioned in dialogue only'], sprites: ['not present before 02:15'] }, visibleObjects: ['Rex’s bat'] } },
      ],
      emotion: 'Frustration and impatience', relationshipGraph: [{ from: 'Rex', to: 'Ellie', label: 'Annoyed because they have different priorities' }],
      timelineData: [{ id: 'before', time: 'Before', label: 'Ellie studies the forest' }, { id: 'now', time: 'Now', label: 'Rex and Victoria complain about the delay' }, { id: 'next', time: 'Next', label: 'The group goes deeper into the forest' }],
      causeEffectData: { cause: 'Ellie keeps stopping to study animals', action: 'Rex complains to Victoria', effect: 'The group’s conflict becomes clear' }, companionPosition: { x: 47, y: 45 }, highlightObject: { name: 'Rex’s bat', reason: 'It helps identify Rex in this scene.' }, visibleObjects: ['Rex’s bat'], voiceNarration: 'Rex and Victoria are discussing Ellie because her interest in nature is slowing their trip.',
    },
    {
      sceneId: 'sf-02', timestamp: 135, subtitle: 'The group enters the sprites’ part of the forest and the creatures finally appear.',
      prompts: [{ id: 'scene', label: 'Explain this scene', question: 'Who are the sprites?', explanation: 'The sprites are small forest creatures who live here and react to the teenagers entering their home.' }, { id: 'emotion', label: 'Feelings', question: 'Why are the sprites cautious?', explanation: 'The sprites are cautious because unfamiliar people have entered the forest they protect.' }],
      characterList: [{ id: 'sprites', name: 'Sprites', role: 'Forest creatures', emotionalState: 'Cautious' }], visibleCharacterIds: ['sprites'], missingCharacterIds: ['ellie', 'rex', 'victoria'], entityConfidence: { sprites: 0.9, ellie: 0, rex: 0, victoria: 0 }, entityEvidence: { sprites: ['small mushroom-like creatures are visible'], ellie: ['not in frame'], rex: ['not in frame'], victoria: ['not in frame'] }, promptSubjects: { scene: ['sprites'], emotion: ['sprites'] },
      storyBeats: [
        { id: 'sf:sprites-arrive', startTime: 135, endTime: 215, phase: 'rising_action', summary: 'The group enters the sprites’ part of the forest and the creatures notice them.', visibleEntityIds: ['sprites'], relationships: ['The sprites are wary of the teenagers entering their home.'], emotions: [{ character: 'Sprites', emotion: 'Cautious', explanation: 'The sprites are cautious because unfamiliar people have entered the forest they protect.' }], objects: ['Mushroom shelter'], causeEffect: [{ cause: 'The teenagers enter the sprites’ home', effect: 'The sprites begin watching them' }], memory: ['The group was already arguing about how to move through the forest.'], promptCandidates: [{ id: 'sf:sprites-cautious', triggerType: 'emotions', question: 'Why are the sprites cautious?', explanation: 'The sprites are cautious because unfamiliar people have entered the forest they protect.', difficultyCategory: 'Feelings', priority: 2, subjectEntityIds: ['sprites'] }], drawerState: { conversationSummary: 'The sprites notice strangers entering their forest.', timelinePosition: 'The forest conflict begins', support: { characters: ['Sprites: Cautious and watching the strangers.'], emotions: ['The sprites are cautious because they are protecting their home.'] } }, confidence: 0.9, visualGrounding: { visibleEntityIds: ['sprites'], missingEntityIds: ['ellie', 'rex', 'victoria'], confidence: { sprites: 0.9, ellie: 0, rex: 0, victoria: 0 }, evidence: { sprites: ['small mushroom-like creatures are visible'] }, visibleObjects: ['Mushroom shelter'] } },
        { id: 'sf:sprites-observing', startTime: 215, endTime: 256, phase: 'rising_action', summary: 'The sprites quietly observe the teenagers from the forest.', visibleEntityIds: ['sprites'], relationships: ['The sprites are deciding whether the teenagers are a danger.'], emotions: [{ character: 'Sprites', emotion: 'Cautious', explanation: 'The sprites are cautious because they are still deciding how to respond to the teenagers.' }], objects: [], causeEffect: [{ cause: 'The sprites see strangers in their home', effect: 'They watch before acting' }], memory: ['The teenagers entered the sprites’ forest without understanding its boundaries.'], promptCandidates: [{ id: 'sf:why-observing', triggerType: 'plot', question: 'Why are the sprites watching them?', explanation: 'The sprites are deciding whether the teenagers are a danger to their forest.', difficultyCategory: 'Story', priority: 2, subjectEntityIds: ['sprites'] }], drawerState: { conversationSummary: 'The sprites watch the teenagers from the forest.', timelinePosition: 'Sprites observing', support: { characters: ['Sprites: Cautious and observing.'], emotions: ['The sprites are cautious because they are deciding whether the teenagers are dangerous.'] } }, confidence: 0.88, visualGrounding: { visibleEntityIds: ['sprites'], missingEntityIds: ['ellie', 'rex', 'victoria'], confidence: { sprites: 0.88, ellie: 0, rex: 0, victoria: 0 }, evidence: { sprites: ['sprites are watching from the forest'] }, visibleObjects: [] } },
        { id: 'sf:first-attack', startTime: 256, endTime: 331, phase: 'climax', summary: 'The sprites attack after deciding the teenagers are a threat.', visibleEntityIds: ['sprites'], relationships: ['The sprites are attacking to protect their forest.'], emotions: [{ character: 'Sprites', emotion: 'Aggressive', explanation: 'The sprites are angry because they believe their home is threatened.' }], objects: [], causeEffect: [{ cause: 'The sprites believe the teenagers threaten the forest', effect: 'They begin attacking' }], memory: ['The sprites had been cautiously observing the teenagers moments earlier.'], promptCandidates: [{ id: 'sf:first-attack-prompt', triggerType: 'emotions', question: 'Why are the sprites attacking?', explanation: 'The sprites believe they must protect their forest from the teenagers.', difficultyCategory: 'Feelings', priority: 2, subjectEntityIds: ['sprites'] }], drawerState: { conversationSummary: 'The sprites attack to protect their forest.', timelinePosition: 'Sprites attack', support: { characters: ['Sprites: Aggressive and protecting their home.'], emotions: ['The sprites are angry because they believe their forest is threatened.'] } }, confidence: 0.91, visualGrounding: { visibleEntityIds: ['sprites'], missingEntityIds: ['ellie', 'rex', 'victoria'], confidence: { sprites: 0.91, ellie: 0, rex: 0, victoria: 0 }, evidence: { sprites: ['sprites are visibly attacking'] }, visibleObjects: [] } },
        { id: 'sf:teenagers-captured', startTime: 331, endTime: 401, phase: 'climax', summary: 'The teenagers are captured as the conflict becomes more dangerous.', visibleEntityIds: ['ellie'], relationships: ['Ellie is in danger because the sprites are trying to control the intruders.'], emotions: [{ character: 'Ellie', emotion: 'Afraid', explanation: 'Ellie is afraid because the group has lost control of the situation.' }], objects: [], causeEffect: [{ cause: 'The sprites’ attack succeeds', effect: 'The teenagers are captured' }], memory: ['The sprites attacked after deciding the teenagers threatened their forest.'], promptCandidates: [{ id: 'sf:captured', triggerType: 'emotions', question: 'Why are the teenagers afraid?', explanation: 'They are afraid because the sprites’ attack has left them trapped.', difficultyCategory: 'Feelings', priority: 2, subjectEntityIds: ['ellie'] }], drawerState: { conversationSummary: 'The teenagers are captured as the forest conflict worsens.', timelinePosition: 'Teenagers captured', support: { characters: ['Ellie: Afraid and trapped.'], emotions: ['Ellie is afraid because the group has lost control of the situation.'] } }, confidence: 0.82, visualGrounding: { visibleEntityIds: ['ellie'], missingEntityIds: ['rex', 'victoria', 'sprites'], confidence: { ellie: 0.85, rex: 0, victoria: 0, sprites: 0 }, evidence: { ellie: ['Ellie is visibly trapped'] }, visibleObjects: [] } },
        { id: 'sf:escape-attempt', startTime: 401, endTime: 450, phase: 'climax', summary: 'Ellie makes a determined attempt to escape the danger.', visibleEntityIds: ['ellie'], relationships: ['Ellie is trying to protect herself while the conflict continues.'], emotions: [{ character: 'Ellie', emotion: 'Determined', explanation: 'Ellie is determined to escape even though she is still in danger.' }], objects: [], causeEffect: [{ cause: 'The teenagers are captured', effect: 'Ellie tries to escape' }], memory: ['The sprites attacked because they believed their forest was threatened.'], promptCandidates: [{ id: 'sf:escape-prompt', triggerType: 'plot', question: 'Why is Ellie trying to escape?', explanation: 'Ellie is trying to get safe after the sprites’ attack trapped the group.', difficultyCategory: 'Story', priority: 2, subjectEntityIds: ['ellie'] }], drawerState: { conversationSummary: 'Ellie tries to escape while the conflict continues.', timelinePosition: 'Escape attempt', support: { characters: ['Ellie: Determined to get safe.'], emotions: ['Ellie is determined even though the danger is not over.'] } }, confidence: 0.86, visualGrounding: { visibleEntityIds: ['ellie'], missingEntityIds: ['rex', 'victoria', 'sprites'], confidence: { ellie: 0.9, rex: 0, victoria: 0, sprites: 0 }, evidence: { ellie: ['Ellie is visibly trying to escape'] }, visibleObjects: [] } },
      ],
      emotion: 'Caution', relationshipGraph: [{ from: 'Sprites', to: 'Teenagers', label: 'Protect their forest home' }], timelineData: [{ id: 'before', time: 'Before', label: 'The teenagers argue' }, { id: 'now', time: 'Now', label: 'Sprites appear' }, { id: 'next', time: 'Next', label: 'The forest reacts' }], causeEffectData: { cause: 'The teenagers enter the sprites’ home', action: 'The sprites notice them', effect: 'The forest conflict begins' }, companionPosition: { x: 59, y: 51 }, highlightObject: { name: 'Mushroom shelter', reason: 'It shows the sprites’ forest home.' }, visibleObjects: ['Mushroom shelter'], voiceNarration: 'The sprites appear only now, after the teenagers have entered their part of the forest.',
    },
    {
      sceneId: 'sf-03', timestamp: 450, subtitle: 'The conflict in the forest reaches its resolution.',
      prompts: [{ id: 'scene', label: 'Explain this scene', question: 'How is the problem solved?', explanation: 'The conflict settles once the characters understand why the forest and its creatures reacted to the group.' }, { id: 'before', label: 'Remember', question: 'What caused this?', explanation: 'The trouble began when the group ignored the forest and the sprites’ home.' }],
      characterList: [{ id: 'sprites', name: 'Sprites', role: 'Forest creatures', emotionalState: 'Relieved' }], visibleCharacterIds: ['sprites'], entityConfidence: { sprites: 0.85 }, entityEvidence: { sprites: ['sprites are visible during the resolution'] }, promptSubjects: { scene: ['sprites'], before: ['sprites'] },
      storyBeats: [
        { id: 'sf:sprites-attack', startTime: 450, endTime: 468, phase: 'climax', summary: 'The sprites attack as Ellie tries to defend herself.', visibleEntityIds: ['ellie', 'sprites'], relationships: ['The sprites are angry because they believe the teenagers have threatened their forest.'], emotions: [{ character: 'Ellie', emotion: 'Frightened', explanation: 'Ellie is frightened because the sprites are attacking and the conflict has become dangerous.' }, { character: 'Sprites', emotion: 'Angry', explanation: 'The sprites are angry because they are protecting their forest home.' }], objects: [], causeEffect: [{ cause: 'The group ignored the sprites’ forest home', effect: 'The sprites attack and Ellie has to defend herself' }], memory: ['Rex and Victoria were already impatient with Ellie before the forest conflict began.'], promptCandidates: [{ id: 'sf:dangerous-conflict', triggerType: 'plot', question: 'How did the conflict become so dangerous?', explanation: 'The group entered the sprites’ forest home, and the sprites now believe they must protect it.', difficultyCategory: 'Story', priority: 3, subjectEntityIds: ['ellie', 'sprites'] }, { id: 'sf:sprites-attacking', triggerType: 'emotions', question: 'Why are the sprites attacking?', explanation: 'The sprites are angry because they are trying to protect their forest.', difficultyCategory: 'Feelings', priority: 2, subjectEntityIds: ['sprites'] }, { id: 'sf:ellie-defending', triggerType: 'emotions', question: 'Why is Ellie defending herself?', explanation: 'Ellie is frightened and is trying to stay safe during the attack.', difficultyCategory: 'Feelings', priority: 1, subjectEntityIds: ['ellie'] }], drawerState: { conversationSummary: 'The sprites attack while Ellie tries to defend herself.', timelinePosition: 'Climax', support: { characters: ['Ellie: Frightened and defending herself.', 'Sprites: Angry and protecting the forest.'], emotions: ['Ellie is frightened because the attack has become dangerous.', 'The sprites are angry because they believe their home is threatened.'], relationships: ['The sprites are attacking because they believe the teenagers threatened their forest.'], memory: ['The conflict began when the group entered the sprites’ forest home.'] } }, confidence: 0.91, visualGrounding: { visibleEntityIds: ['ellie', 'sprites'], missingEntityIds: ['rex', 'victoria'], confidence: { ellie: 0.93, sprites: 0.9, rex: 0, victoria: 0 }, evidence: { ellie: ['Ellie is visibly defending herself'], sprites: ['Sprites are visibly attacking'] }, visibleObjects: [] } },
        { id: 'sf:forest-resolution', startTime: 468, endTime: null, phase: 'resolution', summary: 'The forest is calm again and the conflict is over.', visibleEntityIds: ['ellie', 'sprites'], relationships: ['Ellie and the sprites no longer need to fight.'], emotions: [{ character: 'Ellie', emotion: 'Relieved', explanation: 'Ellie is relieved because the immediate danger has ended.' }, { character: 'Sprites', emotion: 'Calm', explanation: 'The sprites are calm now that the threat to their forest has passed.' }], objects: ['Forest clearing'], causeEffect: [{ cause: 'The characters understand the forest’s boundaries', effect: 'The conflict ends and the forest becomes calm again' }], memory: ['The sprites attacked because they believed their forest home was threatened.'], promptCandidates: [{ id: 'sf:conflict-over', triggerType: 'plot', question: 'How is the conflict over?', explanation: 'The characters understand why the sprites reacted, so they no longer need to fight.', difficultyCategory: 'Story', priority: 2, subjectEntityIds: ['ellie', 'sprites'] }], drawerState: { conversationSummary: 'The forest is calm again and the conflict is over.', timelinePosition: 'Resolution', support: { characters: ['Ellie: Relieved that the danger has passed.', 'Sprites: Calm now that their forest is safe.'], emotions: ['The immediate danger is over, so everyone can calm down.'], memory: ['The conflict began because the sprites believed their home was threatened.'] } }, confidence: 0.92, visualGrounding: { visibleEntityIds: ['ellie', 'sprites'], missingEntityIds: ['rex', 'victoria'], confidence: { ellie: 0.88, sprites: 0.9, rex: 0, victoria: 0 }, evidence: { ellie: ['Ellie is visible after the conflict'], sprites: ['Sprites are calm in the forest clearing'] }, visibleObjects: ['Forest clearing'] } },
      ],
      emotion: 'Relief', relationshipGraph: [{ from: 'Sprites', to: 'Teenagers', label: 'The conflict has settled' }], timelineData: [{ id: 'before', time: 'Before', label: 'The forest conflict' }, { id: 'now', time: 'Now', label: 'The conflict settles' }, { id: 'next', time: 'Next', label: 'The forest is safe again' }], causeEffectData: { cause: 'The group understands the forest’s boundaries', action: 'The conflict is resolved', effect: 'The forest becomes calm again' }, companionPosition: { x: 49, y: 46 }, highlightObject: { name: 'Forest clearing', reason: 'It marks the resolution.' }, visibleObjects: ['Forest clearing'], voiceNarration: 'The conflict settles after the group understands why the forest reacted.',
    },
  ],
}
