import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRightLeft, Edit3, X } from 'lucide-react'
import type { AccessibilityProfile } from '../types/accessibility-profile'

type ProfileEditorProps = { profile: AccessibilityProfile; onClose: () => void; onEdit: () => void; onSwitchCompanion: () => void }

export function ProfileEditor({ profile, onClose, onEdit, onSwitchCompanion }: ProfileEditorProps) {
  return <AnimatePresence><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="min-h-screen bg-[radial-gradient(circle_at_80%_0%,rgba(78,146,200,.3),transparent_28%),#071a3b] p-5 text-white"><section className="mx-auto mt-10 max-w-2xl rounded-3xl border border-white/15 bg-[#0b2856]/90 p-6 shadow-2xl backdrop-blur sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-bold tracking-[.18em] text-amber-200">COMPANION PROFILE</p><h1 className="mt-2 font-serif text-4xl">{profile.companionProfile.name}</h1><p className="mt-1 text-sm text-blue-100">{profile.companionProfile.personality} companion · {profile.companionProfile.appearance}</p></div><button onClick={onClose} aria-label="Close profile editor" className="grid h-10 w-10 place-items-center rounded-full bg-white/10"><X size={18}/></button></div><dl className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white/[.06] p-4"><dt className="text-xs text-blue-200">Language simplification</dt><dd className="mt-1 font-semibold">{profile.aiProfile.detailLevel}</dd></div><div className="rounded-2xl bg-white/[.06] p-4"><dt className="text-xs text-blue-200">Visual assistance</dt><dd className="mt-1 font-semibold">{profile.aiProfile.preferredVisualAssistance.length ? 'Enabled' : 'Minimal'}</dd></div><div className="rounded-2xl bg-white/[.06] p-4"><dt className="text-xs text-blue-200">Prompt style</dt><dd className="mt-1 font-semibold">{profile.aiProfile.interactionStyle}</dd></div><div className="rounded-2xl bg-white/[.06] p-4"><dt className="text-xs text-blue-200">Voice</dt><dd className="mt-1 font-semibold">{profile.companionProfile.voice} · {profile.companionProfile.voiceSpeed}</dd></div></dl><div className="mt-8 flex flex-wrap gap-3"><button onClick={onEdit} className="inline-flex items-center gap-2 rounded-full bg-amber-300 px-5 py-3 text-sm font-bold text-[#17264a]"><Edit3 size={16}/>Edit Profile</button><button onClick={onSwitchCompanion} className="inline-flex items-center gap-2 rounded-full border border-white/20 px-5 py-3 text-sm font-semibold"><ArrowRightLeft size={16}/>Switch Companion</button></div></section></motion.div></AnimatePresence>
}
