import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, BookOpen, Loader2, Send, Upload } from 'lucide-react'
import { bookBackendService, type BookChapter } from './services/backend/BookBackendService'
import { companionProfilePayload } from './services/backend/profilePayload'
import { useAccessibilityProfile } from './hooks/useAccessibilityProfile'

type BookViewerProps = { onBack: () => void }
export function BookViewer({ onBack }: BookViewerProps) {
  const { profile } = useAccessibilityProfile(); const input = useRef<HTMLInputElement>(null)
  const [bookId, setBookId] = useState(''); const [status, setStatus] = useState(''); const [progress, setProgress] = useState(0); const [chapterNumber, setChapterNumber] = useState(1); const [chapter, setChapter] = useState<BookChapter | null>(null); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState(''); const [error, setError] = useState('')
  const begin = async (id: string) => { setError(''); setBookId(id); await bookBackendService.start(id, companionProfilePayload(profile)); setStatus('Extracting text'); setProgress(5) }
  useEffect(() => { void bookBackendService.dune().then(({ book_id }) => setBookId(book_id)).catch((e: unknown) => setError(e instanceof Error ? e.message : 'The Dune example is unavailable.')) }, [])
  useEffect(() => { if (bookId && !status) void begin(bookId).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Could not start Dune processing.')) }, [bookId, status, profile])
  useEffect(() => { if (!bookId || status === 'complete' || status === 'failed') return; const timer = window.setInterval(() => void bookBackendService.status(bookId).then((next) => { setStatus(next.status); setProgress(next.percentage); if (next.status === 'complete') setStatus('complete'); if (next.status === 'failed') setError(next.error ?? 'Book processing failed.') }).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Could not check book processing.')), 1800); return () => window.clearInterval(timer) }, [bookId, status])
  useEffect(() => { if (bookId && status === 'complete') void bookBackendService.chapter(bookId, chapterNumber).then(setChapter).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Could not load this chapter.')) }, [bookId, chapterNumber, status])
  const upload = async (file: File) => { try { const uploaded = await bookBackendService.upload(file); await begin(uploaded.book_id) } catch (e) { setError(e instanceof Error ? e.message : 'Could not upload this book.') } }
  const ask = async () => { if (!bookId || !question.trim()) return; try { const result = await bookBackendService.chat(bookId, chapterNumber, question, companionProfilePayload(profile)); setAnswer(result.answer); setQuestion('') } catch (e) { setError(e instanceof Error ? e.message : 'Companion is unavailable.') } }
  return <main className="movie-experience selector-page"><div className="screen-header"><button className="ghost-btn" onClick={onBack}><ArrowLeft size={16}/> Back</button><h1><BookOpen size={20}/> Dune</h1><button className="primary-btn" onClick={() => input.current?.click()}><Upload size={15}/> Upload a book</button><input ref={input} className="sr-only" type="file" accept="application/pdf,.epub,text/plain,.txt" onChange={(event) => { const file = event.target.files?.[0]; event.currentTarget.value = ''; if (file) void upload(file) }}/></div>{!bookId ? <section className="loading"><Loader2 className="spin"/><div><strong>Loading Dune</strong><p>Connecting to the included Dune reading companion.</p></div></section> : status !== 'complete' ? <section className="loading" aria-live="polite"><Loader2 className="spin"/><div><strong>Creating your MagiFab reading companion…</strong><p>{status || 'Waiting to start'} · {progress}%</p><p>Extracting text → Understanding chapters → Building character relationships → Creating accessibility explanations</p></div></section> : <section className="book-reading-shell"><nav className="book-reader-toolbar"><button onClick={() => setChapterNumber(Math.max(1, chapterNumber - 1))}>Previous chapter</button><strong>{chapter?.title ?? `Chapter ${chapterNumber}`}</strong><button onClick={() => setChapterNumber(chapterNumber + 1)}>Next chapter</button></nav><article className="book-reader-page"><h2>{chapter?.title}</h2><p>{chapter?.summary}</p><h3>Characters</h3><p>{chapter?.characters.map((item) => `${item.name}: ${item.description}`).join(' · ') || 'No character card was generated for this section.'}</p><h3>Memory aid</h3><p>{chapter?.memoryAids.join(' ')}</p><h3>Visual relationship map</h3><p>{chapter?.visualRelationshipMap.nodes.join(' ↔ ')}</p></article><aside className="book-companion-chat"><p>Ask your companion about this chapter.</p>{answer && <p className="companion-chat-message assistant">{answer}</p>}<div><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Who is that? What is happening?"/><button onClick={() => void ask()} aria-label="Send question"><Send size={16}/></button></div></aside></section>}{error && <p className="error-message">{error}</p>}</main>
}
